# Generated by Django 4.1 on 2023-09-15 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField()),
                ('mask_length', models.IntegerField(default=24, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(8)])),
                ('tcp_ports', models.JSONField()),
                ('udp_ports', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('tcp_ports', models.JSONField()),
                ('udp_ports', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=18)),
                ('vendor', models.CharField(max_length=128)),
                ('tcp_services', models.JSONField()),
                ('udp_services', models.JSONField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
